version: 0.1

phases:
  build:
    commands:
      - echo Build started
      - mvn test
  post_build:
    commands:
      - echo Build completed
      - mvn package
artifacts:
  files:
    - target/aws-build-test-maven-project-0.0.1-SNAPSHOT.jar